// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv_ftRjPrf1R6ndCusoAfkecbSBmdoaSM',
    appId: '1:726375595612:web:77a9d4cb7b418c6a553099',
    messagingSenderId: '726375595612',
    projectId: 'pet-shop-boyz',
    authDomain: 'pet-shop-boyz.firebaseapp.com',
    storageBucket: 'pet-shop-boyz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkcOem8_mhHJYPk9iYUZGai43q9mZc5F4',
    appId: '1:726375595612:android:ac0b44ae23d83725553099',
    messagingSenderId: '726375595612',
    projectId: 'pet-shop-boyz',
    storageBucket: 'pet-shop-boyz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwYsxF4KqQSNA8yV9HFGM9aTc5cfu06BM',
    appId: '1:726375595612:ios:41c55dfad80a355c553099',
    messagingSenderId: '726375595612',
    projectId: 'pet-shop-boyz',
    storageBucket: 'pet-shop-boyz.appspot.com',
    iosClientId: '726375595612-d3gqmilf2dof397fh1jqro2odtbi0d43.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoPetShop',
  );
}
